-- ============================================================
-- COMPRA BOA JF — Mercados reais de Juiz de Fora
-- Lista fornecida pelo cliente, com endereços reais.
-- Coordenadas (latitude/longitude) serão preenchidas na Etapa
-- de Otimização de Rota — por enquanto ficam em branco (NULL).
-- ============================================================

insert into markets (name, address, neighborhood, erp_system, active) values
('Bahamas Independência', 'Av. Pres. Itamar Franco, 2115', 'São Mateus', null, true),
('Colina Gourmet', 'Av. Pres. Itamar Franco, 2760', 'São Mateus', null, true),
('Bife de Grife', 'Av. Pres. Itamar Franco, 2542', 'São Mateus', null, true),
('Puramente', 'Av. Pres. Itamar Franco, 2099', 'São Mateus', null, true),
('Araujo Mercado', 'Av. Pres. Itamar Franco, 2080', 'São Mateus', null, true),
('Armazém Coluna', 'Rua São Mateus, 158', 'São Mateus', null, true),
('Empório e Distribuidora Glória', 'Rua São Mateus, 176', 'São Mateus', null, true),
('Mercado Fazendão', 'Rua São Mateus, 600', 'São Mateus', null, true),
('Empório Trem Bão', 'Rua São Mateus, 681', 'São Mateus', null, true),
('Meu Armazém Hortifruti', 'Rua São Mateus, 991', 'São Mateus', null, true),
('Empório Bahamas São Mateus', 'Rua São Mateus, 1030', 'São Mateus', null, true),
('Terê Folhas Hortifruti', 'Rua São Mateus, 443', 'São Mateus', null, true),
('Mercado Boas Frutas', 'Rua São Mateus, 408', 'São Mateus', null, true),
('Supermercado BH Estrela Sul', 'Ladeira Alexandre Leonel, 200', 'Cascatinha', null, true),
('Supermercado Pais & Filhos', 'Av. Olegário Maciel, 2205', 'São Mateus/Paineiras', null, true),
('Colina Gourmet Posto', 'Av. Olegário Maciel, 1002', 'Paineiras', null, true),
('Bary Empório e Frios', 'Rua Padre Café, 273', 'São Mateus', null, true),
('Mercado São Mateus', 'Rua Morais e Castro, 856', 'São Mateus', null, true),
('Empório Bahamas Cascatinha', 'Av. Dr. Paulo Japiassu Coelho, 548', 'Cascatinha', null, true),
('Bahamas Express Independência', 'Av. Presidente Itamar Franco, 3600', 'Cascatinha', null, true),
('Mercado Sampaio', 'Av. Dr. Paulo Japiassu Coelho, 38', 'Cascatinha', null, true),
('Mercado Japiassu', 'Av. Dr. Paulo Japiassu Coelho, 553', 'Cascatinha', null, true),
('Carrefour Hipermercado', 'Av. Rio Branco, 5001', 'Graminha', null, true),
('Bahamas São Vicente 24HS', 'Av. Rio Branco, 3760', 'Alto dos Passos', null, true),
('Hortifruti Rio Branco', 'Av. Rio Branco, 3550', 'Alto dos Passos', null, true),
('Empório Bahamas Rio Branco', 'Av. Rio Branco, 2872', 'Centro', null, true),
('Supermercado Pais & Filhos Rio Branco', 'Av. Rio Branco, 2805', 'Centro', null, true),
('Supermercados BH Rio Branco', 'Av. Rio Branco, 1973', 'Centro', null, true),
('Bahamas Manoel Honório', 'Av. Rio Branco, 700', 'Manoel Honório', null, true),
('Empório Bahamas Santo Antônio', 'Rua Santo Antônio, 375', 'Centro', null, true),
('Supermercados BH Hiper', 'Rua Roberto de Barros, 241', 'Centro', null, true),
('Bahamas Getúlio Vargas', 'Rua Mal. Floriano Peixoto, 270', 'Centro', null, true),
('Supermercados BH Deodoro', 'Rua Marechal Deodoro, 214', 'Centro', null, true),
('Bahamas Express Marechal', 'Rua Marechal Deodoro, 862', 'Centro', null, true),
('Empório Raízes', 'Av. Getúlio Vargas, 200', 'Centro', null, true),
('Bahamas Av. Brasil', 'Av. Brasil, 90', 'Centro', null, true),
('Assaí Atacado e Varejo', 'Av. Brasil, 601', 'Santa Tereza', null, true),
('Supermercados BH Posto Mariano Procópio', 'Av. Brasil, 6123', 'Mariano Procópio', null, true),
('BH Supermercados Mariano Procópio', 'Av. Brasil, 6345', 'Mariano Procópio', null, true),
('Supermercados BH Barão de Cataguases', 'Rua Barão de Cataguases, 195', 'Centro', null, true),
('Bahamas Grama', 'Rua Diomar Monteiro, 126', 'Grama', null, true),
('Bahamas Linhares', 'Rua Diva Garcia, 1160', 'Linhares', null, true),
('Bahamas Poço Rico', 'Av. Francisco Valadares, 36', 'Poço Rico', null, true),
('Bahamas Santa Luzia', 'Rua Ibitiguaia, 551', 'Santa Luzia', null, true),
('Oba Oba', 'Rua Ibitiguaia, 346', 'Santa Luzia', null, true),
('Hortifruti Boa Vista', 'Rua Ibitiguaia esquina Rua Porto das Flores', 'Santa Luzia', null, true),
('Bahamas Santa Terezinha', 'Rua Dr. José Eutrópio, 330', 'Santa Terezinha', null, true),
('Supermercados BH Santa Terezinha', 'Av. Rui Barbosa, 591', 'Santa Terezinha', null, true),
('Bahamas São Pedro', 'Rua José Lourenço, 710', 'São Pedro', null, true),
('Supermercado BH São Pedro', 'Rua José Lourenço Kelmer, 1200', 'São Pedro', null, true),
('Rei do Arroz - Super Mais', 'Av. Pres. Costa e Silva, 2587', 'São Pedro', null, true),
('Bahamas Mix Álvaro José Rodrigues', 'Rua Álvaro José Rodrigues, 1200', 'São Pedro', null, true),
('Mercado Comprove', 'Av. Pres. Costa e Silva, 1996', 'São Pedro', null, true),
('Supermix', 'Av. Pres. Costa e Silva, 2184', 'São Pedro', null, true),
('Banca do Zé', 'Av. Pres. Costa e Silva, 2310', 'São Pedro', null, true),
('Hortifruti Santa Felicidade', 'Rua José Lourenço Kelmer, 975', 'São Pedro', null, true),
('Bahamas Teixeiras', 'Rua Dr. Costa Reis, 849', 'Teixeiras', null, true),
('Açougue e Mercado Avelar', 'Av. Deusdedith Salgado, 1565', 'Teixeiras', null, true),
('Supermercado Pais e Filhos Benfica', 'Rua Martins Barbosa, 270', 'Benfica', null, true),
('Supermercado Pais e Filhos Borboleta', 'Rua Irmão Menrado, 17', 'Borboleta', null, true),
('Supermercado Pais e Filhos Francisco Bernardino', 'Av. Pres. Juscelino Kubitschek, 789', 'Francisco Bernardino', null, true),
('Supermercado Pais e Filhos Milho Branco', 'Av. Ver. Raymundo Hargreaves, 50', 'Fontesville', null, true),
('Supermercado Max Pais e Filhos Nova Era', 'Av. Presidente Juscelino Kubitschek, 5571', 'Nova Era', null, true),
('Bahamas Mix Salvaterra', 'Av. Deusdedith Salgado, 4992', 'Salvaterra', null, true),
('Supermercado BH Salvaterra', 'Av. Deusdedith Salgado, 4088', 'Salvaterra', null, true),
('Martminas', 'Av. Deusdedith Salgado, 4895', 'Salvaterra', null, true),
('BH Atacado e Varejo', 'Av. Antônio Simão Firjam, 320', 'Distrito Industrial', null, true),
('Mineirão Atacarejo', 'Av. Garcia Rodrigues Paes, 12001', 'Distrito Industrial', null, true),
('Atacadão', 'Av. Garcia Rodrigues Paes, 12415', 'Distrito Industrial', null, true),
('BH Supermercados Bom Clima', 'Rua Paracatu, 444', 'Bom Clima', null, true),
('Bahamas Express Jardim Glória', 'Av. dos Andradas, 1147', 'Jardim Glória', null, true),
('Mercado Sacola Cheia', 'Av. dos Andradas, 888', 'Morro da Glória', null, true),
('Mercado Bianca', 'Av. dos Andradas, 966', 'Jardim Glória', null, true),
('Bahamas Mix Santa Catarina', 'Rua Benjamin Guimarães, 315', 'Santa Catarina', null, true),
('Bahamas Mix Barbosa Lage', 'Av. Antônio Weitzel, 669', 'Barbosa Lage', null, true),
('Hortifruti Bom Gosto', 'Rua Elmaia Cunha, 366', 'Jardim de Alá', null, true),
('Varejão Rocha', 'Rua Luiz Fellet, 313', 'Santo Antônio', null, true);
