-- ============================================================
-- COMPRA BOA JF — Catálogo de produtos (várias categorias)
-- Código de barras (EAN) fica em branco por enquanto: será
-- preenchido automaticamente quando os mercados começarem a
-- enviar os arquivos reais via ERP (Etapa 5), que já trazem o
-- código de barras de cada item.
-- ============================================================

insert into products (name, brand, category, unit) values
('Arroz Branco Tipo 1', 'Tio João', 'Cereais e Grãos', '5kg'),
('Arroz Branco Tipo 1', 'Camil', 'Cereais e Grãos', '5kg'),
('Arroz Integral', 'Tio João', 'Cereais e Grãos', '1kg'),
('Feijão Carioca', 'Camil', 'Cereais e Grãos', '1kg'),
('Feijão Preto', 'Kicaldo', 'Cereais e Grãos', '1kg'),
('Macarrão Espaguete', 'Adria', 'Cereais e Grãos', '500g'),
('Macarrão Parafuso', 'Renata', 'Cereais e Grãos', '500g'),
('Farinha de Trigo', 'Dona Benta', 'Cereais e Grãos', '1kg'),
('Farinha de Mandioca', 'Yoki', 'Cereais e Grãos', '500g'),
('Aveia em Flocos', 'Quaker', 'Cereais e Grãos', '500g'),
('Fubá Mimoso', 'Yoki', 'Cereais e Grãos', '500g'),
('Óleo de Soja', 'Soya', 'Mercearia', '900ml'),
('Azeite de Oliva Extra Virgem', 'Gallo', 'Mercearia', '500ml'),
('Açúcar Refinado', 'União', 'Mercearia', '1kg'),
('Açúcar Cristal', 'Caravelas', 'Mercearia', '1kg'),
('Sal Refinado', 'Cisne', 'Mercearia', '1kg'),
('Café Torrado e Moído', 'Pilão', 'Mercearia', '500g'),
('Café Torrado e Moído', 'Três Corações', 'Mercearia', '500g'),
('Molho de Tomate', 'Quero', 'Mercearia', '340g'),
('Extrato de Tomate', 'Elefante', 'Mercearia', '340g'),
('Vinagre de Álcool', 'Castelo', 'Mercearia', '750ml'),
('Maionese', 'Hellmann''s', 'Mercearia', '500g'),
('Ketchup', 'Heinz', 'Mercearia', '397g'),
('Mostarda', 'Hemmer', 'Mercearia', '200g'),
('Biscoito Cream Cracker', 'Adria', 'Mercearia', '200g'),
('Biscoito Recheado Chocolate', 'Nestlé', 'Mercearia', '140g'),
('Achocolatado em Pó', 'Nescau', 'Mercearia', '400g'),
('Gelatina em Pó', 'Royal', 'Mercearia', '20g'),
('Leite Integral', 'Itambé', 'Laticínios', '1L'),
('Leite Desnatado', 'Piracanjuba', 'Laticínios', '1L'),
('Queijo Mussarela', 'Polenghi', 'Laticínios', 'kg'),
('Queijo Minas Frescal', 'Sem marca', 'Laticínios', 'kg'),
('Requeijão Cremoso', 'Catupiry', 'Laticínios', '200g'),
('Manteiga com Sal', 'Aviação', 'Laticínios', '200g'),
('Margarina', 'Qualy', 'Laticínios', '500g'),
('Iogurte Natural', 'Itambé', 'Laticínios', '170g'),
('Iogurte Grego', 'Vigor', 'Laticínios', '100g'),
('Coca-Cola', 'Coca-Cola', 'Bebidas', '2L'),
('Guaraná Antarctica', 'Antarctica', 'Bebidas', '2L'),
('Água Mineral sem Gás', 'Crystal', 'Bebidas', '1,5L'),
('Suco de Laranja Integral', 'Del Valle', 'Bebidas', '1L'),
('Refrigerante Guaraná', 'Itubaína', 'Bebidas', '2L'),
('Cerveja Pilsen', 'Skol', 'Bebidas', 'lata 350ml'),
('Cerveja Pilsen', 'Brahma', 'Bebidas', 'lata 350ml'),
('Picanha Bovina', 'Sem marca', 'Carnes e Aves', 'kg'),
('Alcatra Bovina', 'Sem marca', 'Carnes e Aves', 'kg'),
('Carne Moída', 'Sem marca', 'Carnes e Aves', 'kg'),
('Peito de Frango', 'Sadia', 'Carnes e Aves', 'kg'),
('Frango Inteiro Congelado', 'Perdigão', 'Carnes e Aves', 'kg'),
('Linguiça Toscana', 'Sadia', 'Carnes e Aves', 'kg'),
('Bacon em Cubos', 'Sadia', 'Carnes e Aves', '150g'),
('Banana Prata', 'Sem marca', 'Hortifruti', 'kg'),
('Maçã Gala', 'Sem marca', 'Hortifruti', 'kg'),
('Tomate', 'Sem marca', 'Hortifruti', 'kg'),
('Cebola', 'Sem marca', 'Hortifruti', 'kg'),
('Batata Inglesa', 'Sem marca', 'Hortifruti', 'kg'),
('Alface', 'Sem marca', 'Hortifruti', 'unidade'),
('Cenoura', 'Sem marca', 'Hortifruti', 'kg'),
('Limão Tahiti', 'Sem marca', 'Hortifruti', 'kg'),
('Pão Francês', 'Sem marca', 'Padaria', 'kg'),
('Pão de Forma', 'Pullman', 'Padaria', '500g'),
('Pão de Forma Integral', 'Wickbold', 'Padaria', '500g'),
('Papel Higiênico Folha Dupla', 'Neve', 'Higiene e Limpeza', '12 rolos'),
('Sabonete em Barra', 'Dove', 'Higiene e Limpeza', '90g'),
('Pasta de Dente', 'Colgate', 'Higiene e Limpeza', '90g'),
('Shampoo', 'Seda', 'Higiene e Limpeza', '325ml'),
('Detergente Líquido', 'Ypê', 'Higiene e Limpeza', '500ml'),
('Sabão em Pó', 'Omo', 'Higiene e Limpeza', '1kg'),
('Água Sanitária', 'Qboa', 'Higiene e Limpeza', '1L'),
('Amaciante de Roupas', 'Comfort', 'Higiene e Limpeza', '1L'),
('Desinfetante', 'Pinho Sol', 'Higiene e Limpeza', '500ml');
